#!/bin/bash

echo "## Pulling"
git pull

echo "## Building anchor"
cd /workspaces/formal-verification/Synchronicity/workspace/Synchronicity || exit
make

echo "## Building server"
cd /workspaces/formal-verification/Synchronicity/workspace/web/ || exit
make

echo "## Starting Server"
cd /workspaces/formal-verification/Synchronicity/workspace/web/ || exit
sudo /usr/bin/python3 -u server.py -t 80

exit 0
